name: Password Generator CI

on:
  push:
    branches: ["**"]     # Run on all branches
  pull_request:
    branches: ["**"]     # Run on PRs from any branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Install dependencies
        run: go mod download

      - name: Build
        run: go build ./...

      - name: Run tests
        run: go test ./... -v

      - name: Run vet
        run: go vet ./...
